---
title: "Analysis Plan"
author: "Cole B. Brookson"
date: "5/20/2020"
output: html_document
---
## Step by Step for Bayesian DEBtox Model Fitting

### Individual-level Modeling

Goal of the individual-level model is to quantify effects of microplastics on growth and reproduction via the DEBtox model. There are 5 models of the DEBtox framework, two direct effect models (hazard & costs) and three indirect models (growth, assimilation, maintenance).
#### Growth:
$$ GROWTH: \frac{dl}{dt} = r\frac{f+g}{f + g(l+s)}(f-l)$$
$$ REPRODUCTION: R = \frac{R_M}{1-l^3_p} \left( fl^2\frac{g(1+s) + l}{g(1+s) + f}-l^3_p\right)$$
#### Assimilation:
$$ GROWTH: \frac{dl}{dt} = r\frac{f+g}{f(1-s)+g}(f(1-s)-l)$$

$$ REPRODUCTION: R = \frac{R_M}{1-l^3_p}\left(f(1-s)l^2\frac{g+ l}{g+g(1-s)}-l^3_p\right)$$

#### Maintenance:
$$ GROWTH: \frac{dl}{dt} = r(f-l(1+s))$$

$$ REPRODUCTION: R = \frac{R_M}{1-l^3_p}(1+s)\left(fl^2\frac{g(1+s)^{-1} + l}{g+ f}-l^3_p\right)$$

#### Costs:
$$ GROWTH: \frac{dl}{dt} = r(f-l)$$
$$ REPRODUCTION: R = \frac{R_M}{1-l^3_p}\left(fl^2\frac{g + l}{g + f}-l^3_p\right)(1+s)^{-1}$$

#### Hazard:
$$ GROWTH: \frac{dl}{dt} = r(f-l)$$
$$ REPRODUCTION: R = \frac{R_M}{1-l^3_p}\left(fl^2\frac{g + l}{g + f}-l^3_p\right)e^{-s}$$

Model end points are body length $L$ (or the scaled body length $l = \frac{L}{L_m}$, where $L_m$ is the control max body length) and the reproduction rate $R$ (number of offspring per mother per time unit). These are functions of exposure time $t$ and exposure concentration $c$. So thee are seven parameters:

1. $L_m$ - max body length
2. $l_p$ - scaled body length at puberty
3. $r$ - von Bertalanffy growth rate
4. $R_M$ - maximum reproduction rate 
5. $NEC$ - the No Effect Concentration
6. $c_*$ - tolerance concentration (according to the effect model)
7. $k_e$ - elimination rate

$L_m, r, l_p, R_M$ are common to all organisms. In addition, the theoretical scaled length $l_{h,i}$, and reproduction rate $R_{h,i}$ are latent variables in this framework. The scaled concentration in the organisms $c_{q}$ is defined as $\frac{dc_q}{dt} = k_e(c-c_q)$. 

The stress induced by the toxicant (plastic in our case) is modeled as a stress function $s(c_q(t,c))$ where $c_q$ is the internal concentration scaled by a bioconcentration factor, so that $c_q$ is homogenous to an exposure concentration. The value of the stress function is positive when the scaled concentration inside the organisms ($c_q$), exceeds the NEC. This is modeled by 
$$s(c_q) = c^{-1}_* (c_q - NEC)_+$$ where $(c_q-NEC)_+ = max(0, c_q - NEC)$. c_* is the tolerance concentration, where $* = A, G, M, R, or H$ depending on the effect model considered. 





Two important assumptions of direct effects on reproduction:

1. there is an additional mortality during oogenesis (hazard model)
2. OR there is an increase in the energy costs per egg (cost model)

Three assumptions of indirect effects on reproduction

    1. There is additional growth costs (growth model)
    2. There is reduced incoming inergy (assimilation model)
    3. There is additional maintenance costs (maintenance model)

Model end points are body length $L$ or the scaled body length $l = L/L_m$ where $L_m$ is the control max body length and the reproduction rate $R$ (# of offspring per mother per time unit). These are expressed as functions of the two covariates: exposure time $t$ and the exposure concentration $c$. 

There are 7 parameters of interest involved in the equations:

1. max body length (Lm, milimetres)
2. scaled body length at puberty (lp, dimensionless)
3. von Bertalanffy growth rate (gamma, d^-1)
4. max reproduction rate (Rm,   d^-1)
5. the No effect concentration (NEC, mass L^-1)
6. tolerance concentration (c* = H, R, A, G, or M according to the effect model)
7. elimination rate (ke d-1)

Lm, gamma, lp, and Rm are common to all organisms in an experiment and do not depend on concentration
Lm, and Rm are not always reached by the organisms affected by a contaminant

  End points body length and cumulative reproduction data supposedly follow normal distributions
  for body length with a mean equal to the theoretical body length and a standard deviation (sigma g)
  and the cum. reprod with a mean equal to the cumulative number of offspring per mother and a standard deviation sigma r
  Sigma g represents the invidual variability of body length data with variability between beakers ignored
  and sigma r represents the variability of reproduction between beakers. Scaled length (lh,i) and reproduction rate, Rh,i,
  which are usually end points in DEBtox models are latent variables in the Bayesian framework and depend directly on parameters

## Equations

For the control organisms:
$$\frac{dl}{dt} = r(f-1)$$

$$ R = \frac{R_M}{l-l^3_{p}} * (fl^2 \frac{g+l}{g+f} - l^3_{p})$$

